name: camera_macos_plus
description: macOS camera package implementation. Supports both internal and external cameras, can take pictures and record video with audio as well.
version: 0.0.1
homepage: https://github.com/hm21/camera_macos_plus/
repository: https://github.com/hm21/camera_macos_plus/
documentation: https://github.com/hm21/camera_macos_plus/
funding:
  - https://github.com/sponsors/hm21

topics:
  - camera
  - video-recorder
  - recorder
  - picture

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      macos:
        pluginClass: CameraMacosPlugin
